# Generated by Django 4.1 on 2024-12-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('priority', models.CharField(choices=[('2', 'Средний'), ('3', 'Высокий'), ('1', 'Низкий')], max_length=1)),
                ('isitdone', models.BooleanField()),
            ],
        ),
    ]
