# Generated by Django 4.1 on 2024-12-21 10:42

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateField(default=django.utils.datetime_safe.datetime.now),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('2', 'Средний'), ('1', 'Низкий'), ('3', 'Высокий')], max_length=1),
        ),
    ]
