# Generated by Django 4.1 on 2024-12-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_deadline_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Низкий', 'Низкий(3)'), ('Средний', 'Средний(2)'), ('Высокий', 'Высокий(1)')], max_length=7),
        ),
    ]
