# Generated by Django 4.1 on 2024-12-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_task_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Средний', 'Средний(2)'), ('Высокий', 'Высокий(1)'), ('Низкий', 'Низкий(3)')], max_length=7),
        ),
    ]
