# Generated by Django 4.1 on 2024-12-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Средний', 'Средний(2)'), ('Низкий', 'Низкий(3)'), ('Высокий', 'Высокий(1)')], max_length=7),
        ),
    ]
